content/urls.py
from django.urls import path
from content import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.homepage, name='homepage'), #Here I need to add the webflow part
    path('add/', views.add, name='add'),
    path('<int:content_id>', views.details, name='details'),
    path('link/<int:content_id>', views.link, name='link'),
    path('readerpage/<int:content_id>', views.readerpage, name='readerpage'),
    path('thank_you/<int:content_id>', views.thank_you, name='thank_you'),

]


# path('readerpage/<int:content_id>/add_review',
#      views.add_review, name='add_review'),

user_testing/urls.py
from django.contrib import admin
from django.urls import path, include
from content import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('content/', include('content.urls')),
]

content/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.db.models import Avg, Count, Min, Sum


class Content(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    reviews_total = models.FloatField(null=True)
    pub_date = models.DateTimeField(null=True)

    def _str_(self):
        return self.title

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')


class Review(models.Model):
    content = models.ForeignKey(Content, null=True, on_delete=models.CASCADE)
    name = models.CharField(null=True, max_length=500)
    pub_date = models.DateTimeField(null=True)
    interest = models.CharField(null=True, max_length=500)
    interest_rating = models.IntegerField(null=True)
    clarity = models.CharField(null=True, max_length=500)
    clarity_rating = models.IntegerField(null=True)
    brevity = models.CharField(null=True, max_length=500)
    brevity_rating = models.IntegerField(null=True)
    general_comments = models.CharField(null=True, max_length=500)
    avg_rating = models.FloatField(null=True)
    id = models.AutoField(primary_key=True)

    def _str_(self):
        return self.title

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

# 1. What is the aggregated avg value of readability rating? - make a function?
# 2. What is the aggretaged avg value of actionability rating?
# 3. What is the aggregated avg value of them both?
# 4. What is the aggregated avg value for all ratings

content/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    name = forms.CharField(max_length=10, label='What is your name?')
    interest_rating = forms.ChoiceField(label='How interesting is the piece on a scale of 1-5?',
                                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    interest = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'What is uninteresting? What do you suggest be rewritten to better sustain your interest?', 'cols': 30, 'rows': 4}))
    clarity_rating = forms.ChoiceField(label='Rate how clear you think the piece was on a scale of 1-5',
                                       choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    clarity = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'What’s unclear? Are you left with any unaswered questions?', 'cols': 30, 'rows': 4}))
    brevity_rating = forms.ChoiceField(label='How would you rate the content in terms of brevity on a scale of 1-5',
                                       choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    brevity = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'If you had to delete 20% what would you remove? ', 'cols': 30, 'rows': 4}))
    general_comments = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'General comments? ', 'cols': 30, 'rows': 8}))

    class Meta:
        model = Review
        fields = ['name', 'interest_rating', 'interest',
                  'clarity_rating', 'clarity', 'brevity_rating', 'brevity', 'general_comments']

content/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Review, Content
from django.db.models import Avg, Count, Min, Sum
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from .forms import ReviewForm
from django.views.generic.edit import FormView
from django.utils import timezone


@login_required(login_url="homepage")
def home(request):
    content = Content.objects.annotate(
        avg=Avg('review__avg_rating')).filter(user=request.user)
    total = Content.objects.filter(user=request.user).count()
    # Also send pub_dateo of the review

    return render(request, 'content/home.html', {'content': content, 'total': total})


def homepage(request):
    return redirect("http://test-188175.webflow.io")


@login_required(login_url="/accounts/signup")
def add(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['body']:
            content = Content()
            content.title = request.POST['title']
            content.body = request.POST['body']
            content.user = request.user
            content.pub_date = timezone.datetime.now()
            content.save()
            return redirect('/content/link/' + str(content.id))
        else:
            return render(request, 'content/add.html', {'error': 'You need to fill in all information'})
    else:
        return render(request, 'content/add.html')


@login_required(login_url="/accounts/signup")
def details(request, content_id):
    content = get_object_or_404(
        Content.objects.annotate(
            avg_ir=Avg('review__interest_rating'),
            avg_cr=Avg('review__clarity_rating'),
            avg_br=Avg('review__brevity_rating'),
            avg=Avg('review__avg_rating')
        ),
        pk=content_id)
    return render(request, 'content/details.html', {'content': content, 'reviews': Review.objects.filter(content_id=content_id)})


@login_required(login_url="/accounts/signup")
def link(request, content_id):
    content = get_object_or_404(Content, pk=content_id)
    return render(request, 'content/link.html', {'content': content})


def thank_you(request, content_id):
    content = get_object_or_404(Content, pk=content_id)
    return render(request, 'content/thank_you.html', {'content': content})


def readerpage(request, content_id):
    content = get_object_or_404(Content, pk=content_id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.content = content
            interest_rating = form.cleaned_data['interest_rating']
            interest = form.cleaned_data['interest']
            clarity_rating = form.cleaned_data['clarity_rating']
            clarity = form.cleaned_data['clarity']
            brevity_rating = form.cleaned_data['clarity_rating']
            brevity = form.cleaned_data['clarity']
            general_comments = form.cleaned_data['general_comments']
            review.avg_rating = (float(interest_rating) +
                                 float(clarity_rating) + float(brevity_rating)) / 3
            review.pub_date = timezone.datetime.now()
            review.save()
            return redirect('/content/thank_you/' + str(content.id))
    else:
        form = ReviewForm()
    context = {'content': content, 'form': form}
    return render(request, 'content/readerpage.html', context)

# How can I calculate the avg_rating?

# def add_review(request, content_id):
#     content = get_object_or_404(Content, pk=content_id)
#     if request.POST['readability'] and request.POST['readability_rating'] and request.POST['actionability'] and request.POST['actionability_rating'] and request.POST['general_comments']:
#         review = Review()
#         review.readability = request.POST['readability']
#         review.readability_rating = request.POST['readability_rating']
#         review.actionability = request.POST['actionability']
#         review.actionability_rating = request.POST['actionability_rating']
#         review.general_comments = request.POST['general_comments']
#         review.avg_rating = (float(review.readability_rating) +
#                              float(review.actionability_rating)) / 2
#         review.content = content
#         review.save()
#         return redirect('home')
#     else:
#         return HttpResponseRedirect(reverse('readerpage', args=(content_id,)))

content/templates/content/add.html
{% extends 'base.html' %}

{% block content %}

{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}



</div>

<br/><br/><br/><br/>

    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <h3> Create Content </h3>
                    <form method="POST" action="{% url 'add' %}">
                    {% csrf_token %}
                        <br/>
                        <input type='text' name='title' placeholder="Title" class="form-control"/>
                        <br/>
                         <textarea class="form-control" name='body' rows="20" placeholder="Body"></textarea>
                        <br/>
                        <br/>
                        <div class= "row">
                            <div class ="col-2 mx-auto">
                                <button class="btn btn-success btn-block" type="submit">Create!</button>
                                </form>
                            </div>
                        </div>
            </div>
        </div>
            <br/>
            <br/>

        </div>
    </div>

{% endblock %}

content/templates/content/details.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

  <br/><br/><br/><br/> <!-- vertical spacing -->

  <div class="row">
    <div class="col-8 mx-auto">
        <h1 class="text-center"> {{content.title}} </h1>
        <p class="text-center"> {{content.body}}  </p>
    </div>
  </div>

<br/>
<br/>
<br/>

{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}


<div class="row">

    <div class="col-2">
      <!-- horizontal spacing -->
    </div>

    <div class="col-2">
        <div class="card shadow-sm bg-white rounded ">
          <div class=" mx-auto"> <p class="pt-3"> Overall Rating: {{ content.avg |floatformat:1 }} </p>  </div>
        </div>
    </div>
    <div class="col-2 ">
        <div class="card shadow-sm bg-white rounded ">
          <div class=" mx-auto"> <p class="pt-3"> Interest: {{ content.avg_ir |floatformat:1}} </p>  </div>
        </div>
    </div>
    <div class="col-2">
        <div class="card shadow-sm bg-white rounded ">
          <div class=" mx-auto"> <p class="pt-3"> Clarity: {{ content.avg_cr |floatformat:1 }} </p> </div>
        </div>
    </div>
    <div class="col-2 ">
        <div class="card shadow-sm bg-white rounded ">
          <div class=" mx-auto"> <p class="pt-3"> Brevity: {{ content.avg_br |floatformat:1 }} </p> </div>
        </div>
    </div>

</div>

<br/><br/> <!-- vertical spacing -->

{% for review in reviews reversed %}

<div class="row">
  <div class="col-2">
      <!-- horizontal spacing -->
  </div>

  <div class="col-8 ">
    <div class="card text">
      <div class="card-header">
        <div class="row">
          <div class="col-3">
            <div class="text-primary"> {{ review.name }} </div>
          </div>
          <div class="col-6">
            <!-- horizontal spacing -->
          </div>
          <div class="col-3">
            <div class="float-right text-secondary"> {{ review.pub_date_pretty }} </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title font-strong">Overall Rating: {{review.avg_rating |floatformat:1 }} </h5>
        <p class="card-text"> {{review.general_comments}} </p>

      <div class="collapse" id="{{review.id}}">
      <hr/>


        <h5 class="card-title"> Interest Rating: {{review.interest_rating |floatformat:1 }} </h5>
        <p class="card-text"> Question: What is unintersting? What do you suggest be rewritten to better sustain your interest? <br/>
        Answer: {{review.interest}} </p>
      <hr/>

        <h5 class="card-title"> Clarity Rating: {{review.clarity_rating |floatformat:1 }} </h5>
        <p class="card-text"> Question: What’s unclear? Are you left with any unaswered questions? <br/> Answer: {{review.clarity}} </p>

      <hr/>

        <h5 class="card-title"> Brevity Rating: {{review.brevity_rating |floatformat:1 }} </h5>

        <p class="card-text"> Question: If you had to delete 20% what would you remove? <br/> Answer: {{review.brevity}}  </p>
      <hr/>
      </div>

      </div>

      <div class="card-footer text-muted text-center">
        <a href="#" class="btn" data-toggle="collapse" data-target="#{{review.id}}">
          <div class="row">
          <div> Click to see full review </div>
          </div>
          <!-- <span class="oi oi-caret-bottom"></span> -->
        </a>

      </div>
    </div>
  </div>
</div>

<br/>

{% endfor %}


<br/><br/> <!-- vertical spacing -->

<a href="{% url 'readerpage' content.id %}">  <p class="text-center"> Copy and send this link to the readers you want feedback from </p> </a>


</div>
</div>

<br/>

<!--   <div class="card col-8 mx-auto shadow-sm pt-3 pr-4 pl-4 mb-4 bg-white rounded">
    <div class="row">
      <div class ="col-3 mb-3 text-primary"> Jakob Tolstrup </div>
    </div>
    <div class="row">
      <div class ="col mb-3 text-muted"> Aug 25 </div>
    </div>
    <div class="row">
      <div class="card col-3 shadow-sm pt-3 pr-3 pl-3 pb-3 mb-2 ml-3 mr-1 bg-white rounded ">
        <div class=" mx-auto"> Avg Rating: 4,5 </div>
      </div>
    </div>
    <div class="row">
      <div class="card col-3 shadow-sm pt-3 pr-3 pl-3 pb-3 mb-2 ml-3 mr-1 bg-white rounded ">
        <div class=" mx-auto"> Readability: 4,5 </div>
      </div>
    </div>
    <div class="row">
      <div class="card col-3 shadow-sm pt-3 pr-3 pl-3 pb-3 mb-4 ml-3 mr-1 bg-white rounded ">
        <div class=" mx-auto"> Actionability: 4,5 </div>
      </div>
    </div>
  </div> -->

{% endblock %}

content/templates/content/home.html
{% extends 'base.html' %}


{% block content %}

<div class="container">

    <br/><br/><br/><br/> <!-- vertical spacing -->
    <div class="row">

        <div class="col-2 my-div">
            <!-- horizontal spacing -->
        </div>

        <div class="col-4 my-div">
            <h3> Your Content </h3>
        </div>

        <div class="col-4 my-div ">
             <a href="{% url 'add' %}">
             <button type="button" class="btn btn-success float-right" >
                Create
             </button>
              </a>
        </div>

    </div>

    <br/> <!-- vertical spacing -->

    <!-- second row -->
    <div class="row">
        <div class="col-2 my-div">
            <!-- horizontal spacing -->
        </div>
        <div class="col-4 my-div">
            <p> Total ({{ total }}) </p>
        </div>
    </div>

    <br/> <!-- vertical spacing -->

    <!-- third row -->
    <div class="row">

        <div class="col-2 my-div">
            <!-- horizontal spacing -->
        </div>


        <!-- Here we have the pieces of content -->
        <div class="col-8 my-div">
            {% for content in content.all reversed %}
                <div class="card-deck" onclick="window.location='{% url 'details' content.id %}';" style="cursor: pointer;">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <!-- Here the row begins -->
                            <div class="row">
                                <div class="col">
                                    <div class="row my-row">
                                        <div class="col">
                                             <h4 class="card-title pricing-card-title"> {{ content.title }}</h4>
                                        </div>
                                    </div>
                                    <div class="row my-row">
                                        <div class="col">
                                            <p> Rating: {{ content.avg | floatformat:1 }}</p> <!-- I need to change this to another color -->
                                        </div>
                                        <div class="col">
                                            <p> Reviews: {{ content.review_set.count }} </p>
                                        </div>
                                        <div class="col">
                                            <p> {{ content.pub_date_pretty }} </p> <!-- I need to change this to another color -->
                                        </div>
                                        <div class="col-5">
                                        </div>
                                    </div> <!-- row end -->
                                </div>
                            </div> <!-- row end -->

                            <!-- Here the row stops -->
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    <!-- row 3 end  -->
    </div>

  <br/><br/><br/><br/><br/><br/><br/> <!-- vertical spacing -->


<!-- container div -->
</div>


{% endblock %}

content/templates/content/homepage.html
{% extends 'base.html' %}

{% block content %}

<div style="background-color: #6C9C9D">

<div class="row">
    <div class="offset-1 col-4 px-3 py-3 pt-md-5 pb-md-4">
        <br/>
        <h1 style="color:white">Get feedback on your content </h1> <!-- Make sure the font is helvetica neue -->
        <p> FeedbackBuddy makes it easy to get quality feedback on content from your target demographic </p>
        <button class="btn btn-primary"> Get Started</button>
    </div>
    <!-- <div class="offset-1 col-5 px-3 py-3 pt-md-5 pb-md-4 align-baseline">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="550" height="230" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em"></text></svg>
    </div> -->
</div>
<br/><br/><br/>
<br/><br/><br/>

</div>
<br/>
<br/>
<div class="row">
    <div class="col-4 offset-1">
        <h3 style="color:#C98770"> How it works </h3>
    </div>
</div>

<br/><br/>

<div class="row">
    <div class="container col-3 offset-1">
       <span class="oi oi-plus text-primary"></span>
       <p class="mt-2">  <strong> Step 1:  Add your content </p> </strong>
       <p> Lorem ipsum sinor dolet rem ipsum sinor dolet  rem ipsum sinor dolet Lorem ipsum sinor dolet rem ipsum </p>
    </div>
    <div class="container col-3 mx-auto">
        <span class="oi oi-target text-primary"></span>
    <p class="mt-2"> <strong> Step 2:  Select target audience </p> </strong>
    <p> Lorem ipsum sinor dolet rem ipsum sinor dolet  rem ipsum sinor dolet Lorem ipsum sinor dolet rem ipsum </p>
    </div>
     <div class=" offset-1-right container col-3 ">
        <span class="oi oi-comment-square text-primary"></span>
        <p class="mt-2"> <strong> Step 3: Recieve feedback  </p> </strong>
        <p> Lorem ipsum sinor dolet rem ipsum sinor dolet  rem ipsum sinor dolet Lorem ipsum sinor dolet rem ipsum </p>
    </div>
</div>

<br/>
<br/>


{% endblock %}

content/templates/content/link.html
{% extends 'base.html' %}

{% block content %}


<br/><br/><br/><br/>

<div class="container">

<div class="row">
    <div class="col-6 mx-auto d-flex align-items-center">
        <h2 class="mx-auto"> Your content has been created! </h2>
    </div>
</div>



<div class="row">
    <div class="col-8 mx-auto">
        <hr/>
    </div>
</div>

<br/>

<div class="row">
    <div class="col-6 mx-auto ">
        <a href="{% url 'readerpage' content.id %}">  <p class="text-center"> Copy and send this link to the readers you want feedback from </p> </a>
    </div>
</div>


<br/>

<!-- <div class="row">
    <div class="col ">
        <div class="d-flex justify-content-center">
            <button type="button" class="btn btn-outline-success ">Copy Link</button>
        </div>
    </div>
</div> -->




<!-- <div class="row">
    <div class="col-4 mx-auto">
        <a href="{% url 'readerpage' content.id %}"> <p class="text-center"> Send this link to the person you want feedback from </p> </a>
    </div>
</div> -->




    <br/>
<div class="row">
    <div class="col-4 mx-auto ">

    </div>
</div>

<div class="row">
    <div class="col-4 mx-auto">
        <button class="btn btn-primary d-flex mx-auto">
        <a href="{% url 'home' %}" class="navbar-brand text-white">  <span class="oi oi-arrow-circle-left" style="font-size:25px; vertical-align: middle;"></span> <span> Return to home </span> </a>
        </button>
    </div>
</div>

</div>


{% endblock %}

content/templates/content/readerpage.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<br/><br/><br/><br/>

<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
        <h1 class="text-center"> {{content.title}} </h1>
        <p class="text-center"> {{content.body}} </p>
    </div>
  </div>

<br/>
<br/>
<br/>

<form method="post" class="uniForm">
  {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-6 mx-auto">
        {{ form|crispy }}
      </div>
    </div>
    <div class="col-2"> </div>


</div>

  <div class="row">
    <button type="submit" class="btn btn-primary col-2 mx-auto">Submit</button>
  </div>

</form>

<br/>
<br/>

<!--

    <div class="form-row">
      <div class="form-group col-8 mx-auto">
        {{ form.interest_rating|as_crispy_field }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-8 mx-auto">
        {{ form.interest|as_crispy_field }}
      </div>
    </div>

     <div class="form-row">
        <div class="form-group col-8 mx-auto">
         {{ form.clarity_rating|as_crispy_field }}
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-8 mx-auto">
            {{ form.clarity|as_crispy_field }}
        </div>
      </div>

       <div class="form-row">
        <div class="form-group col-8 mx-auto">
            {{ form.interest_rating|as_crispy_field }}
        </div>
      </div>


       <div class="form-row">
        <div class="form-group col-8 mx-auto">
            {{ form.interest|as_crispy_field }}
        </div>
      </div>


       <div class="form-row">
        <div class="form-group col-8 mx-auto">
            {{ form.brevity_rating|as_crispy_field }}
        </div>
      </div>

       <div class="form-row">
        <div class="form-group col-8 mx-auto">
            {{ form.brevity|as_crispy_field }}
        </div>
      </div>

       <div class="form-row">
        <div class="form-group col-8 mx-auto">
            {{ form.general_comments|as_crispy_field }}
        </div>
      </div>


          <br/>s
          <br/>
    </div>
  </div>
</div>



 <form method="post">
{% csrf_token %}

<div class="form-row">
  <div class="form-group card col-8 mx-auto shadow-sm pt-4 pr-4 pl-4 mb-5 bg-white rounded">
    <div class="card-body form-group">

{{ form | crispy }}
<button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>

</form>
          <br/>
          <br/>
    </div>
  </div>
</div> -->



{% endblock %}

content/templates/content/thank_you.html
{% extends 'base.html' %}

{% block content %}


<br/><br/><br/><br/>

<div class="container">

<div class="row">
    <div class="col-6 mx-auto d-flex align-items-center">
        <h2 class="mx-auto"> Thank you for reviewing: {{ content.title }} </h2>
    </div>
</div>



<div class="row">
    <div class="col-8 mx-auto">
        <hr/>
    </div>
</div>

<br/>


<!-- <div class="row">
    <div class="col ">
        <div class="d-flex justify-content-center">
            <button type="button" class="btn btn-outline-success ">Copy Link</button>
        </div>
    </div>
</div> -->




<!-- <div class="row">
    <div class="col-4 mx-auto">
        <a href="{% url 'readerpage' content.id %}"> <p class="text-center"> Send this link to the person you want feedback from </p> </a>
    </div>
</div> -->




    <br/>
<div class="row">
    <div class="col-4 mx-auto ">

    </div>
</div>

<div class="row">
    <div class="col-4 mx-auto">
        <button class="btn btn-primary d-flex mx-auto">
        <a href="{% url 'home' %}" class="navbar-brand text-white">  <span class="oi oi-arrow-circle-left" style="font-size:25px; vertical-align: middle;"></span> <span> Return to home </span> </a>
        </button>
    </div>
</div>

</div>


{% endblock %}